#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src', 'ping360_sonar')))
from ping360_sonar import main

if __name__ == '__main__':
    main()